### ISSUE TITLE
New Project

### ISSUE THREAD

**Issue by ghost** [lordfriky/web-cfw-loader#41]
You can found an updated version of this github https://thomleg50.github.io/web-cfw-loader/
Add PR and Issue in that.
Thanks @ElijahZAwesome can we talk on discord Thomleg50#2660

**Comment by Enovale** [comment]
Trying to hijack my project is completely unnecessary, If you want to make changes, make a pull request. Even though i'm not updating this, I still take pull requests. All you did was give the website a low resolution, bad background image and spread misinformation. You can use that converter but i specifically added a way to output the hex bytes so that you could make new payloads. Just for you, ill update the payloads now.

**Comment by Enovale** [comment]
In heinsight, i'll apologize about the converter. It's very useful. I didn't realize that it formatted text in a way that works for this site, but the rest of my points still stand.
