### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by Wiilf** [lordfriky/web-cfw-loader#73]
This script has been reworked. Now it reports progress using a progressbar on each step.
**transferIn.onprogress** reports **e.loaded**, so we use that to enable progress reporting.

As our requirements, we've replaced async/await with jQuery deferred objects for library consistency.

**New function:** updateDeviceList() - This listens and populates a <select> element with newly found devices. 
Each device can be selected and automatically connected to via serialNumber from this list.
So we attach these event handlers beforehand.

The code is now pure jQuery as we must conform to our project requirements, but these changes has greatly evolved this loader.
We are not done with this code yet. Reviewing the API limitations in the Windows operating systems, we plan to work at that however possible without the need of alternative OS browsers/shell commands. This is a limitation we are now transitioning toward.

**EDIT:** We've successfully imported 5 separate payloads, working very well.

Your truly, Switch-Torrents ;)

**Comment by lordfriky** [comment]
I don't really want to change the visual aspect of the project nor modify the script that heavily because I have been wanted to do a rewrite of the project a long time ago with a different set of features (although you're always free to do a fork and make all the changes you want as I think you already did).

I just wanted to thank you for your interest in the project because that made me interested to implement the final features I wanted to add to the page.
